// Code generated by Slice Machine. DO NOT EDIT.

import Members from './Members/index.svelte';
import SquadA from './SquadA/index.svelte';
import SquadB from './SquadB/index.svelte';

export const components = {
	members: Members,
	squad_a: SquadA,
	squad_b: SquadB
};
