// Code generated by Slice Machine. DO NOT EDIT.

import Members from './Members/index.svelte';
import SquadA from './SquadA/index.svelte';

export const components = {
	members: Members,
	squad_a: SquadA
};
