// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice = MembersSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
	/**
	 * Slice Zone field in *home*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *home*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *home*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<HomeDocumentData>,
	'home',
	Lang
>;

/**
 * Content for member documents
 */
interface MemberDocumentData {
	/**
	 * name field in *member*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * about field in *member*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.about
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	about: prismic.RichTextField;

	/**
	 * picture field in *member*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.picture
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	picture: prismic.ImageField<never>;

	/**
	 * card field in *member*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member.card
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	card: prismic.LinkField;
}

/**
 * member document from Prismic
 *
 * - **API ID**: `member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<MemberDocumentData>,
	'member',
	Lang
>;

type MemberBDocumentDataSlicesSlice = SquadBSlice;

/**
 * Content for member_b documents
 */
interface MemberBDocumentData {
	/**
	 * name_b field in *member_b*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_b.name_b
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name_b: prismic.KeyTextField;

	/**
	 * about_b field in *member_b*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_b.about_b
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	about_b: prismic.RichTextField;

	/**
	 * picture_b field in *member_b*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_b.picture_b
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	picture_b: prismic.ImageField<never>;

	/**
	 * card_b field in *member_b*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_b.card_b
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	card_b: prismic.LinkField;

	/**
	 * Slice Zone field in *member_b*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: member_b.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<MemberBDocumentDataSlicesSlice>;
}

/**
 * member_b document from Prismic
 *
 * - **API ID**: `member_b`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberBDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<MemberBDocumentData>,
	'member_b',
	Lang
>;

type SquadBDocumentDataSlicesSlice = SquadBSlice;

/**
 * Content for squad_B documents
 */
interface SquadBDocumentData {
	/**
	 * Slice Zone field in *squad_B*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: squad_b.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<SquadBDocumentDataSlicesSlice>
	/**
	 * Meta Description field in *squad_B*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: squad_b.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *squad_B*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: squad_b.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;

	/**
	 * Meta Title field in *squad_B*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: squad_b.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_title: prismic.KeyTextField;
}

/**
 * squad_B document from Prismic
 *
 * - **API ID**: `squad_b`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadBDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<SquadBDocumentData>,
	'squad_b',
	Lang
>;

export type AllDocumentTypes = HomeDocument | MemberDocument | MemberBDocument | SquadBDocument;

/**
 * Primary content in *Members → Items*
 */
export interface MembersSliceDefaultItem {
	/**
	 * member field in *Members → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: members.items[].member
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	member: prismic.ContentRelationshipField;
}

/**
 * Default variation for Members Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembersSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	Simplify<MembersSliceDefaultItem>
>;

/**
 * Slice variation for *Members*
 */
type MembersSliceVariation = MembersSliceDefault;

/**
 * Members Shared Slice
 *
 * - **API ID**: `members`
 * - **Description**: Members
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MembersSlice = prismic.SharedSlice<'members', MembersSliceVariation>;

/**
 * Default variation for SquadA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadASliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *SquadA*
 */
type SquadASliceVariation = SquadASliceDefault;

/**
 * SquadA Shared Slice
 *
 * - **API ID**: `squad_a`
 * - **Description**: SquadA
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadASlice = prismic.SharedSlice<'squad_a', SquadASliceVariation>;

/**
 * Primary content in *SquadB → Items*
 */
export interface SquadBSliceDefaultItem {
	/**
	 * squad_b field in *SquadB → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: squad_b.items[].squad_b
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	squad_b: prismic.ContentRelationshipField;
}

/**
 * Default variation for SquadB Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadBSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	Simplify<SquadBSliceDefaultItem>
>;

/**
 * Slice variation for *SquadB*
 */
type SquadBSliceVariation = SquadBSliceDefault;

/**
 * SquadB Shared Slice
 *
 * - **API ID**: `squad_b`
 * - **Description**: SquadB
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadBSlice = prismic.SharedSlice<'squad_b', SquadBSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			HomeDocument,
			HomeDocumentData,
			HomeDocumentDataSlicesSlice,
			MemberDocument,
			MemberDocumentData,
			MemberBDocument,
			MemberBDocumentData,
			MemberBDocumentDataSlicesSlice,
			SquadBDocument,
			SquadBDocumentData,
			SquadBDocumentDataSlicesSlice,
			AllDocumentTypes,
			MembersSlice,
			MembersSliceDefaultItem,
			MembersSliceVariation,
			MembersSliceDefault,
			SquadASlice,
			SquadASliceVariation,
			SquadASliceDefault,
			SquadBSlice,
			SquadBSliceDefaultItem,
			SquadBSliceVariation,
			SquadBSliceDefault
		};
	}
}
